"""empty message

Revision ID: 82502015d742
Revises: 880b1b79400e
Create Date: 2021-04-19 19:17:29.219899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82502015d742'
down_revision = '880b1b79400e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=254), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
